name=LTR390UVSensor
version=1.0.0
author=matt
maintainer=mumanchu <info@muman.ch>
sentence=LTR390 Ambient Light and UV Sensor with I2C Interface
paragraph=With LUX and UV Index calculations in float and/or integer
category=Sensors
includes=LTR390UVSensor.h
url=https://github.com/mumanchu/LTR390UVSensor
architectures=stm32
